[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build", "npx prisma generate", "ls -la dist/"]

[phases.start]
cmd = "node dist/main.js"

